// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXDAyDXV3-_qPGGlOjkCRdXeLdkzpYeK8',
    appId: '1:759119411396:web:934ba1daba9e0f7d837191',
    messagingSenderId: '759119411396',
    projectId: 'vaelys',
    authDomain: 'vaelys.firebaseapp.com',
    storageBucket: 'vaelys.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhjZ1A1zqtGNrKIO5KJ_UDEwXQc6quBxs',
    appId: '1:759119411396:android:09f2b3f345bf1e2b837191',
    messagingSenderId: '759119411396',
    projectId: 'vaelys',
    storageBucket: 'vaelys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDheG-POpwwv3DHUcnrkUcVOeyu1z0F8_E',
    appId: '1:759119411396:ios:67d607e45843e491837191',
    messagingSenderId: '759119411396',
    projectId: 'vaelys',
    storageBucket: 'vaelys.firebasestorage.app',
    iosBundleId: 'com.example.fashionstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDheG-POpwwv3DHUcnrkUcVOeyu1z0F8_E',
    appId: '1:759119411396:ios:67d607e45843e491837191',
    messagingSenderId: '759119411396',
    projectId: 'vaelys',
    storageBucket: 'vaelys.firebasestorage.app',
    iosBundleId: 'com.example.fashionstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXDAyDXV3-_qPGGlOjkCRdXeLdkzpYeK8',
    appId: '1:759119411396:web:3f7b6c579f566783837191',
    messagingSenderId: '759119411396',
    projectId: 'vaelys',
    authDomain: 'vaelys.firebaseapp.com',
    storageBucket: 'vaelys.firebasestorage.app',
  );
}
